### ISSUE TITLE
Enabling this extension disables the real IntelliSense

### ISSUE THREAD

**Issue by Fanatic17** [mattbierner/vscode-emojisense#12]
Hi, 

i really like this extension but enabling it doesn't show any suggestion from IntelliSense. I don't think this is the desired behaviour of the extension. 

If not can I enable it only in the comments?

**Comment by mattbierner** [comment]
Can you please provide more information about where intellisense does not work? What is the file type and where are you trying to trigger it?

**Comment by Fanatic17** [comment]
Yeah, I'm editing a .csx file recognized as a C# file correctly. Since I activated this extension I didn't get any more suggestion from IntelliSense but I couldn't quite figure out why. So yesterday I tried disabling this extension and it came back to life (e.g. on a list L if i Ctrl+ Space on "L." i got only text suggestions (like words I already typed, but not the methods like Add. Disabling the extension I got back the smart suggestions).

**Comment by mattbierner** [comment]
Did you [configure it for the `csharp` language](https://github.com/mattbierner/vscode-emojisense#per-language-configuration)?

**Comment by Fanatic17** [comment]
I didn't configure anything but the extension was working properly until the last update of VS Code. 
But it shouldn't hinder the real intellisense functionality.
Anyways I'll try configuring or uninstalling and reinstalling the extension, which I like a lot. Hopefully this will solve the problem.

**Comment by mattbierner** [comment]
Closing as out of date / possible resolved
