### ISSUE TITLE
Some emojis missing

### ISSUE THREAD

**Issue by muuvmuuv** [mattbierner/vscode-emojisense#15]
I noticed that this emoji is missing: 🧭

In my Markdown Preview it shows up but in the editor I get that squared box. Searching for it with `:compass:` didn't worked.

**Comment by ctf0** [comment]
same here for all emojis on windows

**Comment by mattbierner** [comment]
What OS and VS Code version was this for?

**Comment by ctf0** [comment]
@mattbierner for my case its on windows 7

**Comment by muuvmuuv** [comment]
Current VS Code and Plugin version on latest MacOS

**Comment by mattbierner** [comment]
That is unrelated to this extension; you should see the same issue if you paste one of the emoji into an editor.

Please file an issue against VS Code proper for this (but test on the latest VS Code insiders build first)
