### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AlexBrasileiro** [mattbierner/vscode-emojisense#18]
- Issue Type: `Performance`
- Extension Name: `emojisense`
- Extension Version: `0.5.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Volumes/Arquivos/bierner.emojisense-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mattbierner** [comment]
Please attach the cpu profile

**Comment by mattbierner** [comment]
Closing as not actionable without profile
