### ISSUE TITLE
Contributes keybinding Ctrl+Shift+I which replaces `Format Document`

### ISSUE THREAD

**Issue by seesemichaelj** [mattbierner/vscode-emojisense#19]
This extension contributes a quick picker for emoji's using the `Ctrl+Shift+I `keybinding. This keybinding conflicts with the `Format Document` command.

If you're stumbling across this issue, this is how I've done a work around:

Open the keyboard shortcuts: `Ctrl+Shift+P` => `Preferences: Open Keyboard Shortcuts (JSON)`

I then redirect the emoji keybinding to `Ctrl+Alt+I` instead of `Ctrl+Shift+I` with the following addition to the JSON array

```json
  ...,
  {
    "key": "ctrl+alt+i",
    "command": "emojisense.quickEmojitext",
    "when": "editorTextFocus"
  },
  {
    "key": "ctrl+shift+i",
    "command": "-emojisense.quickEmojitext",
    "when": "editorTextFocus"
  },
  {
    "key": "ctrl+alt+i",
    "command": "emojisense.quickEmojitextTerminal",
    "when": "terminalFocus"
  },
  {
    "key": "ctrl+shift+i",
    "command": "-emojisense.quickEmojitextTerminal",
    "when": "terminalFocus"
  }
```

**Comment by mattbierner** [comment]
I don't see any default keybindings for these. What os are you on? Are you using a keymap extension?

**Comment by seesemichaelj** [comment]
Hey @mattbierner, I'm on Linux. There are two `Ctrl+Shif+I` keyboard shortcuts whose source are `Default`:

![image](https://user-images.githubusercontent.com/549323/55830378-c3756100-5ade-11e9-92f0-aaa1f3fb34b5.png)

I'm not using a keymap extension

**Comment by mattbierner** [comment]
Sorry, I did not know this keybinding was used on linux. We should come up with a different one for linux users. @seesemichaelj Any suggestions for one?

**Comment by seesemichaelj** [comment]
I'm using `Ctrl+Alt+I` which doesn't conflict with any Linux shortcuts. I would have used `Ctrl+Alt+E` (E for emoji), but it's an awkward movement.

**Comment by rickstaa** [comment]
Is this still planned? I don't see a related pull request. For now, I will use @seesemichaelj shortcut.
