### ISSUE TITLE
Show emoji in completion list

### ISSUE THREAD

**Issue by felixfbecker** [mattbierner/vscode-emojisense#2]
Everything is rendered in a Chrome renderer so VS Code should have no problem showing the actual unicode emoji in the completion list

**Comment by felixfbecker** [comment]
Just noticed it does get shown in the details section upon selection. How about showing it directly in the list like GH does?

**Comment by mattbierner** [comment]
I reverted d493cb2 for 0.2 because solutions that alters the label break the VSCode completion filtering logic. Reopening

**Comment by felixfbecker** [comment]
I think you can provide a different string to filter by than the label

**Comment by mattbierner** [comment]
Yes `filterText` but it actually doesn't work properly in my testing

**Comment by svipben** [comment]
I wanted to create an issue, but I think you're guys talking about the same. In @mattbierner example here https://marketplace.visualstudio.com/items?itemName=bierner.emojisense emojis is icons, but when I install and use it I see only unicode. This plugin can be really good if it shows actual image, not unicode. And by the way, nice work, really good plugin, I will try to use more emojis in my `.MD` :smile:

**Comment by mattbierner** [comment]
Just published 0.3.0 which includes this. Was fixed by 73bd946 with vscode 1.17+
