### ISSUE TITLE
facepalm emojis crash extension host

### ISSUE THREAD

**Issue by kinghat** [mattbierner/vscode-emojisense#22]
![Peek 2019-12-10 12-14](https://user-images.githubusercontent.com/16073360/70557536-9df69680-1b48-11ea-8704-65e699c61946.gif)

**Comment by mattbierner** [comment]
What VS code version and OS?

**Comment by kinghat** [comment]
> What VS code version and OS?

just tested again and it seems to only happen when you do it in a new file, not saved and no extension yet.

> Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-37-generic

**Comment by mattbierner** [comment]
I can't reproduce this in VS Code 1.44

If you still see this, please check to see if pasting in a facepalm emoji also causes a crash. Also make sure to disable other extensions to make sure this one is causing the issue
