### ISSUE TITLE
Emoji suggestion does not show on start of string

### ISSUE THREAD

**Issue by nopeless** [mattbierner/vscode-emojisense#24]
Typing ":" when the string starts doesn't show the emoji suggestion

example

let a ="";

if you type ':' inside those quotes, the extension won't suggest the emojis

**Comment by mattbierner** [comment]
This is by-design currently. Github also does not offer emoji suggestions in this case

We could either:

- Make an exception for the case `":`
- Or make it so that manually triggering intellisense always shows suggestions if you are after a colon, not matter what the preceding character is

**Comment by nopeless** [comment]
I'll close this issue since I got used to typing space and colon now
