### ISSUE TITLE
Angular 6+ version is not supporting this extension

### ISSUE THREAD

**Issue by Shekhar12121** [mattbierner/vscode-emojisense#26]
i have set the setting.json as below : 
`"emojisense.unicodeCompletionsEnabled" : true,
    "emojisense.markupCompletionsEnabled" : true,
    "emojisense.languages": {
      "markdown" : true,
      "plaintext" : true,
      "git-commit" : true,
      "json" : true,
      "javascript" : true,
      "typescript"  :true,
      "nodejs" : true,
      "react" : true
    },
    "typescript.validate.enable": false`

After that when i use emojis, then i got  **compilation error in angular**  like this  :  
` **error TS1127: Invalid character**.

245     console.log("emojis here"😄, 🐒);`

please fix this issue

**Comment by mattbierner** [comment]
I don't understand the issue. Please describe what you are doing and share the invalid code

**Comment by mattbierner** [comment]
Closing due to lack of feedback
