### ISSUE TITLE
Stopped working in VSCode 1.13

### ISSUE THREAD

**Issue by borekb** [mattbierner/vscode-emojisense#4]
I don't see completions in either of my enabled languages. When I write an `:emoji:` manually, I still see preview so the only issue are the completions.

**Comment by mattbierner** [comment]
Sorry, I missed this issue somehow. This should have been fixed already. Please let me know if you are still seeing issues with version 0.3.0 of this extension

**Comment by borekb** [comment]
Thanks, will try. Later, I found out that it had some interference with [Markdown Shortcuts](https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts) extension, I since switched to [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) where it was better.

**Comment by borekb** [comment]
The new previews are nice!
