### ISSUE TITLE
FR: add support for Github Pull Requests and Issues panel

### ISSUE THREAD

**Issue by tyler36** [mattbierner/vscode-emojisense#48]
I recently begun using [Github Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extention.

Emoji sense works great in the "new issue" form. However it does not work in the "Pull Request" panel or "Pull Request" form.

I'm not sure if this intended or not.  It feels like it should work because the "Source Control" panel functions. 

It would be great if this could be made to work as I'm always trying to type an emoji into the pull request title before remember it doesn't work.

VScode: `1.63`
EmojiSense: `0.9.0`
Github Pull Requests and Issues: `0.34.0`

**Comment by mattbierner** [comment]
I believe those forms are webviews so we cannot enable this extension for them

The source control message box on the other hand is a simplified VS Code editor, so it does support extensions
