### ISSUE TITLE
Git commit

### ISSUE THREAD

**Issue by bsvipas** [mattbierner/vscode-emojisense#6]
Hello @mattbierner,

It doesn't work in Git commits... I'm trying to get autocomplete and rendering of emoji, but nothing happens.

```
  "emojisense.languages": {
    "markdown": true,
    "plaintext": {
      "markupCompletionsEnabled": false,
      "emojiDecoratorsEnabled": false
    },
    "git-commit": true
  },
```

VS Code: 1.20.1
OS: macOS

**Comment by linzhaoken** [comment]
I go the same. This is my only purpose to install this plugin, to use it in git commit.

**Comment by mattbierner** [comment]
I can't repo this with the default settings:  

<img width="901" alt="screen shot 2018-06-13 at 11 31 17 pm" src="https://user-images.githubusercontent.com/212305/41395284-edd3edd6-6f61-11e8-946e-972cdfdc7746.png">


Is the language mode of the file (as listed in the status bar) show as `git commit message`? How are you trying to trigger the emoji?

**Comment by bsvipas** [comment]
@mattbierner here:

![image](https://user-images.githubusercontent.com/30043375/41397312-75e2582a-6fbc-11e8-9412-91b76ee41db2.png)

**Comment by mattbierner** [comment]
Yeah that's not something extensions can contribute IntelliSense to currently. Closing as an upstream vscode issue

**Comment by bsvipas** [comment]
Thanks a lot, @mattbierner, as always excellent work!

**Comment by kanlukasz** [comment]
Is it still impossible?
