### ISSUE TITLE
Display emoji suggestion when deleting characters after empty search

### ISSUE THREAD

**Issue by emilioidk** [mattbierner/vscode-emojisense#8]
**Extension version:** 0.4.0
**Problem:** I have noticed that when I start typing the list of suggestions changes to show suggestions for the currently inputted string. If I delete a character, the list gets refreshed. So far so good.
![1](https://user-images.githubusercontent.com/2219357/40971516-365fd704-68be-11e8-8ccc-cad462f2d208.gif)

The problem arises when a partial substring doesn't return any suggestion. In that case the suggestions box disappears which makes sense, but if I delete characters from that string, shouldn't the extension recalculate whether there are any emojis to suggest?
![2](https://user-images.githubusercontent.com/2219357/40971674-a99eff38-68be-11e8-8310-c94bcabf9343.gif)

**Comment by mattbierner** [comment]
This is an upstream bug on VS Code: https://github.com/Microsoft/vscode/issues/51843

You can always manually trigger suggestions using ctrl+space
